
language: r

r:
  - release
  - devel
  - oldrel

cache: packages

r_github_packages:
  - r-lib/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
